### ISSUE TITLE
Questions on functionality

### ISSUE THREAD

**Issue by jeremyjpj0916** [yciabaud/kong-plugin-prometheus#1]
So  this plugin exposes metrics for Prometheus to pull correct? Does it expose the metrics on top of each api at a specific mykongproxy.com/my/proxy/endpoint/prometheus/metrics or something of that sort? As a WIP what is left to work out? My team is interested in Prometheus for Kong and may end up working on something similar.

**Comment by yciabaud** [comment]
Yes it exposes metrics on an admin endpoint like kong:8001/prometheus/metrics

The same endpoint provides metrics for all the enabled apis, for my tests, I have enabled the plugin globally to have the metrics for all my apis.

It is working right now, I wait for some more tests before publishing it for real but you can definitely give it a try!

If this plugin does not fit your needs, we can improve it together. Tell me what you think!

Since it is not published, you need to install the rock with the GitHub release URL. The nginx shared dict I use is only present in the last Kong release (0.11 if I remember well), you will need to create one in a custom nginx config and configure it in the plugin if you use a different version.

**Comment by yciabaud** [comment]
Notice there should be an issue when enabling the plugin for the first time, you probably need to restart Kong to make it work.

**Comment by jeremyjpj0916** [comment]
Thanks for the reply man! We did have a concern with

"
Please keep in mind that all metrics stored by this library are kept in a single shared dictionary (lua_shared_dict). By default, we use the kong_cache shared dict so if you are using it remember to allow extra space to it. While exposing metrics the module has to list all dictionary keys, which has serious performance implications for dictionaries with large number of keys (in this case this means large number of metrics OR metrics with high label cardinality). Listing the keys has to lock the dictionary, which blocks all threads that try to access it (i.e. potentially all nginx worker threads).
"

Another alternative is to say use the statsD plugin pointing to a provisioned statsD instance and then the statsD exporter <- Prometheus. Was there a reason you never went the aforementioned route?  Then you can harness the lightweight UDP protocol statsD employs and not worry about impacting your Gateway node. Our API's deal with 100m transactions+ a day so I am not sure its really ideal to store metrics on the node itself. I don't really have a good way to calculate out how large a  lua_shared_dict would need to be for such volume on a kong cluster nor do I think I even wanna risk blocking nginx worker threads in a production env. I wonder if the caveat you mention is why Kong never did a Prometheus Plugin themselves.

**Comment by yciabaud** [comment]
I understand your concerns, Prometheus is designed to pull metrics from the system periodically so we need to keep some counters in memory.

The maximum size is likely limited if you know the cardinality and the metrics you need.
Statsd may be a better solution for you but if you go with prometheus you will need to load test a node and measure the needed memory to store the metrics.

**Comment by yciabaud** [comment]
The reason the route is missing in the readme is that I did not implemented it at the time I wrote the file and I forgot the add it afterwards ;)

**Comment by jeremyjpj0916** [comment]
Right, I mean ideally we would have 100-300 api's on a Kong cluster and we would want to utilize all 6 of those exposed metrics on a per API basis most likely. Since we will have like 5-6 in a cluster the actual daily volume on a node would not be 100m heh. Lets say 100-200k a day though.

1. Maybe we will test it, based on your initial tests do you have any recommended lua_shared_dict memory setting, one that in your opinion gives so much space it would be a non issue? 

2. Is the mem_cache_size parameter Kong specifies in the kong.conf referring to the same thing you are(kong_cache)? Sorry if I am asking newbie questions, I am still very new to Kong and Prometheus in fact :) .

3. Being a bit new, so for each API exposing these metrics, they get an entry in the lua shared dictionary table(kong_cache by default), is it an entry constantly being updated as a real time value then, node is not really maintaining its past+present metrics, only the present and assume Prometheus is polling every minute or so and is really the keeper of the "history"? Seems Gauge is the best type for the 5/6 exposed metrics. "http_requests_total" should probably be Counter, but it makes sense to kinda reset that daily almost I think so you can see when request totals climb quickly during the day correlate it with more important latency metrics. Or just leave it out all together, but then you lose that sense of usage spikes. I see a reset important because just daily that thing grows out, and eventually the total is so large spikes won't be as noticeable. 

4. So basically for every API you will be almost dedicating a worker thread constantly updating these node metrics. So by design each api now will pretty much hog a worker thread to maintain stat updates, won't all these 100's of threads(api's) have that shared dictionary locked down constantly at that point? 

5. What Kong operations clash with heavy utilization of the (kong_cache)? Cache misses and things like rate limiting right?

**Comment by yciabaud** [comment]
Closing as this is quite old
