### ISSUE TITLE
error when run with kong 0.13

### ISSUE THREAD

**Issue by steinliber** [yciabaud/kong-plugin-prometheus#14]
When run this plugin in kong 0.13, report error below

> 2018/05/28 04:00:07 [debug] 45#0: *5121028 [lua] logger.lua:81: log(): Prometheus: logging metrics...
2018/05/28 04:00:07 [error] 45#0: *5121028 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/prometheus/logger.lua:87: bad argument #1 to 'string_gsub' (string expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'string_gsub'
	/usr/local/share/lua/5.1/kong/plugins/prometheus/logger.lua:87: in function 'log'
	.../local/share/lua/5.1/kong/plugins/prometheus/handler.lua:21: in function <.../local/share/lua/5.1/kong/plugins/prometheus/handler.lua:16>, context: ngx.timer, client: 192.168.141.0, server: 0.0.0.0:8000
2018/05/28 04:00:07 [info] 45#0: *5121026 client 192.168.141.0 closed keepalive connection

**Comment by yciabaud** [comment]
Hello, we pointed out this in #13, we need to update the plugin to managethe breaking changes introduced in Kong 0.13.

It will not work without these changes.
I close this issue but we can discuss it furthermore in #13.
