### ISSUE TITLE
http_upstream_duration_ms_histogram_sum value is -1

### ISSUE THREAD

**Issue by jayhding** [yciabaud/kong-plugin-prometheus#15]
After taking plugin version v0.1.1 into use I have seen below errors from Kong container log.

```
06/06/2018 07:55:192018/06/06 07:55:19 [error] 51#0: *2715 [lua] prometheus.lua:296: log_error(): Error while setting 'http_upstream_duration_ms_histogram_sum{api="XXXX"}' to '-1': 'Value should not be negative', context: ngx.timer, client: 10.130.100.241, server: 0.0.0.0:8000
06/06/2018 07:55:1910.130.100.241 - - [06/Jun/2018:07:55:19 +1000] "GET /health HTTP/1.1" 200 5 "-" "ELB-HealthChecker/2.0"
06/06/2018 07:55:192018/06/06 07:55:19 [error] 51#0: *2717 [lua] prometheus.lua:296: log_error(): Error while setting 'http_upstream_duration_ms_histogram_sum{api="XXXX"}' to '-1': 'Value should not be negative', context: ngx.timer, client: 10.130.100.241, server: 0.0.0.0:8000
06/06/2018 07:55:1910
```

Seems it only happens on one specific api, and `kong_http_request_duration_ms_gauge` for that api is always 0

I have not checked deeply why it happened, just wondering first if you have seen this as well.

**Comment by yciabaud** [comment]
Yes a colleague of mine saw that too, did not had time to investigate neither. Thanks for this issue we need to fix this.

**Comment by ms2008** [comment]
When there is one short circuiting, http_upstream_duration_ms returns a negative duration. 

Reference there: https://github.com/kong/kong/blob/master/kong/plugins/log-serializers/basic.lua#L43

I fix it by zero-out the http_upstream_duration_ms instead of passing it to nginx-lua-prometheus as negative in this pr: #18
