### ISSUE TITLE
The latency metrics is incorrect

### ISSUE THREAD

**Issue by ms2008** [yciabaud/kong-plugin-prometheus#19]
By default, nginx-lua-prometheus use a floating-point number for the elapsed time in seconds (including milliseconds as the decimal part). This place:

https://github.com/yciabaud/kong-plugin-prometheus/blob/3e7e544ac06c99300c07617f39c2102c5288b782/prometheus.lua#L45-L47

But Kong use an interger precision in milliseconds. If we pass it to nginx-lua-prometheus directly, the latency accuracy is lost.
    
There came up with two solutions:

1. Define custom buckets
2. Divided the Kong latency by 1000

**Comment by yciabaud** [comment]
I am sorry I missed that, I guess this repo is becoming less useful now kong is providing a plugin for prometheus but I merged your fix for older versions.

Thanks for your work.
