### ISSUE TITLE
could not migrate postgresql 

### ISSUE THREAD

**Issue by donglei** [yciabaud/kong-plugin-prometheus#2]
we install prometheus plugin for kong, docker build success。while exec kong migrations up --vv command,the plugin prometheus migration not run.
how can i fixed it .
the Dockerfile in https://github.com/donglei/docker-kong/blob/master/centos/Dockerfile

**Comment by yciabaud** [comment]
Hello donglei!

it is nice you use my plugin but be aware that it is still in early stage and I don't use it in production now.

I did not experiment running the migrations yet, I believe my tests ran only on the kong cache.
Can you provide some logs of this error?

**Comment by donglei** [comment]
Thank you for your informing. We use caution in production environments, currently just learning.

kong migrate not show any log about prometheus  plugin, while exec kong run .. cmd error happened.

| 2017/12/13 10:13:58 [warn] postgres database 'kong' is missing migration: (prometheus) 2017-09-23-160000_prometheus_schema_changes
kong_1            | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:149: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
kong_1            | stack traceback:
kong_1            | 	[C]: in function 'assert'
kong_1            | 	/usr/local/share/lua/5.1/kong/init.lua:149: in function 'init'
kong_1            | 	init_by_lua:3: in main chunk

**Comment by yciabaud** [comment]
I am a bit late but in case someone is struggling with this problem, you need to set `LUA_PATH` instead of `KONG_LUA_PACKAGE_PATH` in order to have kong finding your custom plugin on the migration phase.
