### ISSUE TITLE
"WIP - not ready yet"

### ISSUE THREAD

**Issue by chris-scentregroup** [yciabaud/kong-plugin-prometheus#3]
Possible to create a milestone to track what is needed to make it ready for a release?

I can help out as well as this is pretty important for us.

**Comment by yciabaud** [comment]
Yes that's a good idea, I am running it in production now but the metrics are not used for some architecture reasons.

I believe it lacks some load testing and some update process.

How do you want to help?

**Comment by chris-scentregroup** [comment]
Any way I can :)
If we can create a milestone and each ticket, I can see if there is any I can do PRs for - albeit might be a way to learn LUA too.

**Comment by yciabaud** [comment]
Here is the milestone: https://github.com/yciabaud/kong-plugin-prometheus/milestone/1
